.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SP_RESOURCE\.RB" "1" "June 2018" "" ""
.
.SH "NAME"
\fBsp_resource\.rb\fR \- Manage Specify application resources from the command line
.
.SH "SYNOPSIS"
\fBsp_resource\.rb\fR <>
.
.SH "DESCRIPTION"
\fBsp_resource\.rb\fR is a command\-line tool to \.\.\.
.
.SH "FILES"
\fB/usr/local/etc/sp_resource/db\.yml\fR is used \.\.\.
.
.SH "COMMANDS"
.
.SH "OPTIONS"
.
.SH "EXAMPLES"

